"""remove unique from appointment slot

Revision ID: f07b9fa91dbc
Revises: c17117eb2901
Create Date: 2026-02-09 21:44:46.697679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07b9fa91dbc'
down_revision: Union[str, Sequence[str], None] = 'c17117eb2901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_slot_id_key'), 'appointments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('appointments_slot_id_key'), 'appointments', ['slot_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
